### PR TITLE
Use `parse::<Txid>()` in place of `encode::deserialize_hex()`

### LINKED ISSUE #11: Use `pares` instead of  `deserialize_hex` for hash types
One can deserialize a hex string into a `Txid` using either `encode::deserialize_hex()` or `parse::<Txid>()`. Use `parse` everywhere in favour of using standard traits over custom functions.

### PR DESCRIPTION
**Pull request by fedemagnani**
Closes #11

### CODE REVIEW

**Comment by tcharding** [comment]
This is awesome; I had not imagined we would get rid of the `encode::FromHex` error returns - that is cool. Thanks

Can I be a pest and ask you to write a more complete commit log please

Something like

```
Use parse::<Txid> instead of encode::deserialize_hex

Currently, in some places, we use the bespoke `encode::deserialize_hex` function to deserialize txid from a hex string. The `Txid` type provides a `FromStr` impl so we can use `parse::<Txid>()`. This makes the code more easily readable because its a common pattern in Rust.
```

Thanks man. (If you are interested in git commit logs check out the very educational post: https://cbea.ms/git-commit/

**Comment by fedemagnani** [comment]
Thank you guys. I amended the commit including the message sugested. Does it look good? @tcharding

**Review by tcharding — APPROVED** [review]
ACK 6a465b4e881cdab009a447a55d57142d8ed6f0a7

**Review by apoelstra — APPROVED** [review]
ACK 6a465b4e881cdab009a447a55d57142d8ed6f0a7; successfully ran local tests; interesting about the changed error type

**Pull request merged**
