### PR TITLE
Add dev tooling

### PR DESCRIPTION
**Pull request by tcharding**
Add two new tools

- A Perl script to create the rustdocs list found in, for example `types/src/v17/mod.rs`
- A Rust `verify` tool that parses the RPC text file and then greps the codebase doing various checks.

The `verify` tool is so that one can look at the docs for version specific types (the list of method names and implementation status) and have confidence that they are correct.

I'm going to merge and release this without review because its just an additional unreleased dev tool. The fixes included in this PR are what I wanted to have confidence in the next release.

The next thing I want to verify is that the methods documented as returning nothing or stdlib types really do so by either hitting Core or grepping the source ... one day.

### CODE REVIEW

**Comment by tcharding** [comment]
Ugh, I clicked merge instead of ack'ing and using the merge script.

**Comment by tcharding** [comment]
Just crossed my mind that you have been gracious in helping me out with this crate @apoelstra, I merged this to save you the time/effort of looking at it. Didn't mean to brush you. I figured its easier to just pull master and play with the `verify` crate in this PR.

**Comment by apoelstra** [comment]
Yeah, no problem. I don't want to hold you up with process. But if I see stuff that's open I'll probably take a quick look and run through my local CI.

**Comment by apoelstra** [comment]
This PR broke Cargo-minimal.lock (and maybe the other one) by adding the MSRV-incompatible `regex-automata` package.

**Comment by tcharding** [comment]
Oh I should have excluded it from the workspace, woops. How did that pass CI I wonder.

**Comment by tcharding** [comment]
Fixed in #35

**Pull request merged**
